import type { GameConfig } from '../game/types';

export const config: GameConfig = {
    gridRadius: 6,
    buildRadius: 5,
    headerItemCap: 3,
    headerSkillCap: 3,
    saunaHp: 72,
    startingSisu: 10,
    sisuAbilityCost: 5,
    sisuDurationMs: 5000,
    sisuCooldownMs: 12500,
    sisuAttackMultiplier: 1.16,
    sisuDamageMultiplier: 1.32,
    boardCap: 4,
    saunaCap: 1,
    baseRosterCap: 5,
    baseInventoryCap: 2,
    baseItemSlots: 1,
    recruitBaseCost: 6,
    recruitCostStep: 2,
    recruitWaveStep: 1,
    steamPerSaunaWave: 1,
    steamPerBossWave: 4,
    saunaHealPerPrep: 5,
    baseLootChance: 0.18,
    bossLootChance: 1,
    bossEvery: 5,
    cyclePressureBase: 6,
    cyclePressureStep: 5,
    wavePressureStep: 2,
    minSpawnIntervalMs: 400,
    spawnIntervalStepMs: 68,
    lowSisuThreshold: 4,
    lowSaunaHintRatio: 0.45,
    metaShopUnlockCost: 5,
    spawnLanes: [
      { q: 0, r: -6 },
      { q: 6, r: -6 },
      { q: 6, r: 0 },
      { q: 0, r: 6 },
      { q: -6, r: 6 },
      { q: -6, r: 0 }
    ]
  };
