import type { GameContent } from '../game/types';

export const enemyArchetypes: GameContent['enemyArchetypes'] = {
    raider: {
      id: 'raider',
      name: 'Goblin Raider',
      behavior: 'standard',
      description: 'A fast melee pest that rushes the nearest defender and starts stabbing immediately.',
      lore: 'Claims every stolen ladle is a cultural artifact.',
      maxHp: 12,
      damage: 4,
      range: 1,
      attackCooldownMs: 1215,
      moveCooldownMs: 1000,
      fill: '#d96b5a',
      outline: '#6d231f',
      label: 'R',
      threat: 2
    },
    brute: {
      id: 'brute',
      name: 'Stone Brute',
      behavior: 'standard',
      description: 'A slower frontline bruiser with more health and heavier hits than a raider.',
      lore: 'Still convinced doors are a conspiracy against shoulders.',
      maxHp: 22,
      damage: 7,
      range: 1,
      attackCooldownMs: 1560,
      moveCooldownMs: 1185,
      fill: '#c14b3f',
      outline: '#5c1715',
      label: 'B',
      threat: 4
    },
    chieftain: {
      id: 'chieftain',
      name: 'Steam Hog Chieftain',
      behavior: 'standard',
      description: 'An elite lane crusher with boss-tier bulk for a normal wave threat.',
      lore: 'Promoted itself after winning one argument and eating the minutes.',
      maxHp: 52,
      damage: 10,
      range: 1,
      attackCooldownMs: 1300,
      moveCooldownMs: 1080,
      fill: '#8c2d2d',
      outline: '#2f0909',
      label: 'C',
      threat: 10
    },
    pebble: {
      id: 'pebble',
      name: 'Pebble',
      behavior: 'pebble',
      description: 'A tunneling worm boss that hunts beer bottles on its first visit, then returns as a bigger, tankier and slower breach threat.',
      lore: 'Named Pebble by someone who had never seen a pebble before.',
      maxHp: 260,
      damage: 12,
      range: 1,
      attackCooldownMs: 1980,
      moveCooldownMs: 1620,
      fill: '#8a5b3d',
      outline: '#2d1408',
      label: 'P',
      threat: 24
    },
    thirsty_user: {
      id: 'thirsty_user',
      name: 'Thirsty End User',
      behavior: 'swarm',
      description: 'A weak swarm unit that becomes dangerous when too many thirsty users stay alive together.',
      lore: 'Opened eight duplicate tickets because the first seven felt lonely.',
      maxHp: 7,
      damage: 1,
      range: 1,
      attackCooldownMs: 1155,
      moveCooldownMs: 720,
      fill: '#cf7d62',
      outline: '#5f271f',
      label: 'U',
      threat: 2
    },
    electric_bather: {
      id: 'electric_bather',
      name: 'Electric Sauna User',
      behavior: 'electric',
      description: 'A ranged boss that shocks clustered heroes and chains electricity through wet targets.',
      lore: 'Read one safety poster and took it as a personal challenge.',
      maxHp: 104,
      damage: 9,
      range: 2,
      attackCooldownMs: 1390,
      moveCooldownMs: 1045,
      fill: '#5e7fb6',
      outline: '#14243d',
      label: 'E',
      threat: 18
    },
    escalation_manager: {
      id: 'escalation_manager',
      name: 'Escalation Manager',
      behavior: 'summoner',
      description: 'A support boss that summons thirsty users and shrugs off damage while its minions remain alive.',
      lore: 'Has never solved a problem directly when three meetings could do less.',
      maxHp: 126,
      damage: 7,
      range: 2,
      attackCooldownMs: 1465,
      moveCooldownMs: 1065,
      fill: '#7f4f5f',
      outline: '#2b121b',
      label: 'M',
      threat: 20
    }
  };
